using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;
using Entity;

namespace Repository
{
    public class PrintRepo
    {
        Login l = new Login();
        public PrintRepo(Login l)
        {
            this.l = l;
        }
        public void gpdf(List<Orderitem> listoforderitem,string name)
        {
            double tprice=0;
            Document doc = new Document(PageSize.A5, 10, 10, 10, 10);
            PdfWriter.GetInstance(doc, new FileStream(@"F:\10th semester\OOP-2(Practice)\RestaurentManagementSystem/" + name + ".pdf", FileMode.Create));
            doc.Open();
            Font lb = new Font(iTextSharp.text.Font.FontFamily.TIMES_ROMAN, 30, Font.BOLD, BaseColor.GREEN);
            Chunk lbtext=new Chunk("X Restaurant",lb);
            Font ob = new Font(iTextSharp.text.Font.FontFamily.TIMES_ROMAN, 10, Font.ITALIC, BaseColor.BLACK);
            Chunk obtext = new Chunk("Order Id : "+name,ob);
            Font tb = new Font(iTextSharp.text.Font.FontFamily.TIMES_ROMAN, 10, Font.ITALIC, BaseColor.BLACK);
            Chunk tbtext = new Chunk(DateTime.Now.ToString(),tb);
            Paragraph p1=new Paragraph();
            p1.Add(lbtext);
            p1.SpacingBefore = 10;
            p1.SpacingAfter = 5;
            p1.Alignment = Element.ALIGN_CENTER;

            Paragraph p2 = new Paragraph();
            p2.Add(obtext);
            p2.SpacingBefore = 1;
            p2.SpacingAfter = 5;
            p2.Alignment = Element.ALIGN_CENTER;

            Paragraph p3 = new Paragraph();
            p3.Add(tbtext);
            p3.SpacingBefore = 1;
            p3.SpacingAfter = 5;
            p3.Alignment = Element.ALIGN_CENTER;
           
            doc.Add(p1);
            doc.Add(p3);
            doc.Add(p2);
        
            PdfPTable table = new PdfPTable(4);
            //table.SetWidthPercentage =
            //table.DefaultCell.FixedHeight = 15f;
            table.AddCell("Foodid");
            table.AddCell("FoodName");
            table.AddCell("Quantity");
            table.AddCell("Price");
            for (int i = 0; i < listoforderitem.Count; i++)
            {
                tprice = tprice + listoforderitem[i].Totalprice;
                table.AddCell(listoforderitem[i].Foodid);
                table.AddCell(listoforderitem[i].Foodname);
                table.AddCell((listoforderitem[i].Quantity).ToString());
                table.AddCell((listoforderitem[i].Totalprice).ToString());
            }
            doc.Add(table);
            Font bbc = new Font(iTextSharp.text.Font.FontFamily.TIMES_ROMAN, 15, Font.ITALIC, BaseColor.RED);
            Paragraph p4 = new Paragraph("Total Price: "+tprice,bbc);
            p4.SpacingBefore = 15;
            p4.SpacingAfter = 20;
            p4.Alignment = Element.ALIGN_RIGHT;
            doc.Add(p4);

            Font bb = new Font(iTextSharp.text.Font.FontFamily.TIMES_ROMAN, 20, Font.BOLD, BaseColor.BLACK);
            Paragraph p5 = new Paragraph("Please do Visit us Again",bb);
            p5.Alignment = Element.ALIGN_CENTER;
            doc.Add(p5);

            Paragraph p6 = new Paragraph("Order generated by :"+ l.Id);
            p6.Alignment = Element.ALIGN_CENTER;
            doc.Add(p6);

            doc.Close();
        }

    }
}
